выполнил задание 2
korenandr/mentee pull request #5
Opened 2022-01-31 14:58 UTC by Poison1488

2022-01-31 20:12 UTC, korenandr commented on task1/задание_2.py
> +    operashion_cod = input("Введите код операции-")
В коде нужно использовать слова без ошибок. Проверь в переводчике слова операция и код.

2022-01-31 20:14 UTC, korenandr commented on task1/задание_2.py
> +variable_1 = input("Введите любое число-")
имена переменных должны быть осмысленными! Имя переменной должно отображать то, для чего она используется. В данном случае я не понимаю, что означает variable_1

2022-01-31 20:30 UTC, korenandr commented on task1/задание_2.py
> +                while int(variable_3) >= 0:
int(variable_3) ты создаешь новый (времменый int), когда variable_3 уже имеет этот тип (строчкой выше ты ее создал как variable_3 = **int**(variable_1) ). Поэтому происходит лишняя конвертация из int в int.

2022-01-31 20:32 UTC, korenandr requested changes

2022-01-31 20:32 UTC, korenandr commented on task1/задание_2.py
> +                        while int(variable_4) >= 0:
И здесь то же самое

2022-02-04 09:26 UTC, Poison1488 commented
исправил ошибки

2022-02-04 10:03 UTC, korenandr requested changes

2022-02-04 10:03 UTC, wandrounik commented on task1/задание_2.py
> +            if operation_code.isdigit():
В строке #5 ты уже делаешь эту проверку, зачем ее снова делать?

2022-02-04 10:03 UTC, korenandr commented on task1/задание_2.py
> +                while_variable_1 = int(user_variable)
Лучше использовать имя **counter** (что переводится как счетчик)

2022-02-04 10:03 UTC, korenandr commented on task1/залание_3.py
> +l = {}
Зачем в этот пулл реквест добавлять файл из третьего задания?

2022-02-04 10:03 UTC, korenandr commented on task1/задание_2.py
> +                        while_variable_2 = int(user_variable)
Лучше использовать имя, что написал выше

2022-02-04 10:19 UTC, Poison1488 commented
все исправил

2022-02-04 10:27 UTC, korenandr approved these changes

2022-02-04 10:27 UTC, merged